//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.07.03 at 02:32:27 PM BST
//


package com.onlinepayment.onlinepaymentspringbootsoap.OnlinePaymentSpringBoot_Example.onlinepaymentdetail;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for onlinePaymentDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="onlinePaymentDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RRN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BANK_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CARDNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="LANACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CUSTID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ACTIVITYFLAG" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STATUSRRN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="LASTPAYDATE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TRANSNUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="REINSTATED" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "onlinePaymentDetail", propOrder = {
    "rrn",
    "bankcode",
    "cardnumber",
    "lanaccount",
    "custid",
    "activityflag",
    "statusrrn",
    "amount",
    "lastpaydate",
    "transnumber",
    "reinstated"
})
public class OnlinePaymentDetail {


    @XmlAttribute
    @XmlElement(name = "RRN", required = true)
    protected String rrn;
    @XmlAttribute
    @XmlElement(name = "BANK_CODE", required = true)
    protected String bankcode;
    @XmlAttribute
    @XmlElement(name = "CARDNUMBER",required = true)
    protected int cardnumber;
    @XmlAttribute
    @XmlElement(name = "LANACCOUNT", required = true)
    protected String lanaccount;
    @XmlAttribute
    @XmlElement(name = "CUSTID",required = true)
    protected int custid;
    @XmlAttribute
    @XmlElement(name = "ACTIVITYFLAG", required = true)
    protected String activityflag;
    @XmlAttribute
    @XmlElement(name = "STATUSRRN", required = true)
    protected String statusrrn;
    @XmlAttribute
    @XmlElement(name = "AMOUNT",required = true)
    protected int amount;
    @XmlAttribute
    @XmlElement(name = "LASTPAYDATE",required = true)
    protected int lastpaydate;
    @XmlAttribute
    @XmlElement(name = "TRANSNUMBER", required = true)
    protected String transnumber;
    @XmlAttribute
    @XmlElement(name = "REINSTATED", required = true)
    protected String reinstated;

    /**
     * Gets the value of the rrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRRN() {
        return rrn;
    }

    /**
     * Sets the value of the rrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRRN(String value) {
        this.rrn = value;
    }

    /**
     * Gets the value of the bankcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKCODE() {
        return bankcode;
    }

    /**
     * Sets the value of the bankcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKCODE(String value) {
        this.bankcode = value;
    }

    /**
     * Gets the value of the cardnumber property.
     * 
     */
    public int getCARDNUMBER() {
        return cardnumber;
    }

    /**
     * Sets the value of the cardnumber property.
     * 
     */
    public void setCARDNUMBER(int value) {
        this.cardnumber = value;
    }

    /**
     * Gets the value of the lanaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANACCOUNT() {
        return lanaccount;
    }

    /**
     * Sets the value of the lanaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANACCOUNT(String value) {
        this.lanaccount = value;
    }

    /**
     * Gets the value of the custid property.
     * 
     */
    public int getCUSTID() {
        return custid;
    }

    /**
     * Sets the value of the custid property.
     * 
     */
    public void setCUSTID(int value) {
        this.custid = value;
    }

    /**
     * Gets the value of the activityflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIVITYFLAG() {
        return activityflag;
    }

    /**
     * Sets the value of the activityflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIVITYFLAG(String value) {
        this.activityflag = value;
    }

    /**
     * Gets the value of the statusrrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSRRN() {
        return statusrrn;
    }

    /**
     * Sets the value of the statusrrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSRRN(String value) {
        this.statusrrn = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public int getAMOUNT() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAMOUNT(int value) {
        this.amount = value;
    }

    /**
     * Gets the value of the lastpaydate property.
     * 
     */
    public int getLASTPAYDATE() {
        return lastpaydate;
    }

    /**
     * Sets the value of the lastpaydate property.
     * 
     */
    public void setLASTPAYDATE(int value) {
        this.lastpaydate = value;
    }

    /**
     * Gets the value of the transnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSNUMBER() {
        return transnumber;
    }

    /**
     * Sets the value of the transnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSNUMBER(String value) {
        this.transnumber = value;
    }

    /**
     * Gets the value of the reinstated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREINSTATED() {
        return reinstated;
    }

    /**
     * Sets the value of the reinstated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREINSTATED(String value) {
        this.reinstated = value;
    }

}
