//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.03 at 02:32:27 PM BST 
//


package com.onlinepayment.onlinepaymentspringbootsoap.OnlinePaymentSpringBoot_Example.paymentdetailenum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paymentDetail.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="paymentDetail"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RRN"/&gt;
 *     &lt;enumeration value="CUSTID"/&gt;
 *     &lt;enumeration value="CARDNUMBER"/&gt;
 *     &lt;enumeration value="MSGDESCRIPTION"/&gt;
 *     &lt;enumeration value="RESPONSECODE"/&gt;
 *     &lt;enumeration value="AVAILLIMIT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "paymentDetail")
@XmlEnum
public enum PaymentDetail {

    RRN,
    CUSTID,
    CARDNUMBER,
    MSGDESCRIPTION,
    RESPONSECODE,
    AVAILLIMIT;

    public String value() {
        return name();
    }

    public static PaymentDetail fromValue(String v) {
        return valueOf(v);
    }

}
