spring:
  profiles:
    active: local
    default: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    livenessstate:
      enabled: true