//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.03 at 02:32:27 PM BST 
//

//http://onlinepayment.com/spring_boot_soap_example
@javax.xml.bind.annotation.XmlSchema(namespace = "http://onlinepayment.com/spring_boot_soap_example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.onlinepayment.onlinepaymentspringbootsoap.OnlinePaymentSpringBoot_Example;




